### ISSUE TITLE
2 errors when trying to compile

### ISSUE THREAD

**Issue by fletcher100** [QuickBlox/sample-chat-parse-ios#18]
Upon compiling I am getting these two errors:

 no such file or directory: '/Users/fletcher100/Desktop/sample-chat-parse-ios/Pods/Target Support Files/TTTAttributedLabel/TTTAttributedLabel-dummy.m'

clang: error: no input files

Any suggestions?
Thank You.

**Comment by Raikerian** [comment]
Hi!

This project is not released yet, so the code in master branch is not yet compilable. However if you want to see this project now just clone development branch.

**Comment by fletcher100** [comment]
Sounds good, thanks.
